"""Added date to reservations.

Revision ID: f775c4b88a02
Revises: 8254ba424a06
Create Date: 2021-12-07 16:11:18.209927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f775c4b88a02'
down_revision = '8254ba424a06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'date')
    # ### end Alembic commands ###
