"""Removed time from reservations.

Revision ID: eb35fa587b1c
Revises: 73a5cdd21f0f
Create Date: 2021-12-07 15:39:29.084990

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eb35fa587b1c'
down_revision = '73a5cdd21f0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
