"""no unique on description

Revision ID: 307909155265
Revises: 88acfd65d2f7
Create Date: 2021-12-06 21:11:00.612639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307909155265'
down_revision = '88acfd65d2f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('restaurants_description_key', 'restaurants', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('restaurants_description_key', 'restaurants', ['description'])
    # ### end Alembic commands ###
