"""Create cuisines.

Revision ID: 033d24161adc
Revises: 96a470be4dea
Create Date: 2021-12-06 19:05:54.004098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "033d24161adc"
down_revision = "96a470be4dea"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuisines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_foreign_key(None, 'restaurants', 'cuisines', ['cuisine_type'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restaurants', type_='foreignkey')
    op.drop_table('cuisines')
    # ### end Alembic commands ###
