"""temporarily delete notes and party_size columns

Revision ID: 932c5151149c
Revises: eb27649add42
Create Date: 2021-12-08 13:04:51.075923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '932c5151149c'
down_revision = 'eb27649add42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'party_size')
    op.drop_column('reservations', 'notes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('reservations', sa.Column('party_size', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
