"""Added date and time to reservations.

Revision ID: 73a5cdd21f0f
Revises: 8254ba424a06
Create Date: 2021-12-07 15:32:15.127027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73a5cdd21f0f'
down_revision = '8254ba424a06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('time', sa.Time(), nullable=False))
    op.add_column('reservations', sa.Column('date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'date')
    op.drop_column('reservations', 'time')
    # ### end Alembic commands ###
