"""notes and party_size default null.

Revision ID: 78cb545ad299
Revises: 932c5151149c
Create Date: 2021-12-08 13:05:35.209740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78cb545ad299'
down_revision = '932c5151149c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('party_size', sa.Integer(), nullable=True))
    op.add_column('reservations', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'notes')
    op.drop_column('reservations', 'party_size')
    # ### end Alembic commands ###
