"""adding new updated at column

Revision ID: eb27649add42
Revises: bdd1f3263500
Create Date: 2021-12-07 21:54:20.828584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb27649add42'
down_revision = 'bdd1f3263500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('updatedat', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'updatedat')
    # ### end Alembic commands ###
